[package]
name = "svg-to-piet"
version = "0.1.0"
authors = ["Paul Miller <paul@pauljmiller.com>"]
edition = "2018"
license = "MIT/Apache-2.0"

[dependencies]
usvg = "0.6"
svg-piet-macro = { path = "macro" }
pietify = {path = "pietify"}